### ISSUE TITLE
List items difficult to keep apart

### ISSUE THREAD

**Issue by CodeWringer** [CodeWringer/ambersteel-foundryVTT#294]
Adjust the styling so that list items are set apart properly. This problem is especially noticeable with skill list items, which seem to sit very tightly packed together. 

Perhaps the following style might suffice:
```CSS
.custom-system-list-item {
    margin-bottom: 1rem;
    border-radius: 10px;
    border: 1px solid #818181d9;
}
```
